"""add lead value columns

Revision ID: c463800be556
Revises: b12dd9604f76
Create Date: 2026-09-26 09:42:26.273391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c463800be556'
down_revision: Union[str, Sequence[str], None] = 'b12dd9604f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('load_zone', sa.String(length=20), nullable=True))
    op.add_column('leads', sa.Column('battery_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('leads', sa.Column('recommended_kwh', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('sizing_reason', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('value', sa.Float(), nullable=True))
    op.add_column('leads', sa.Column('expected_value', sa.Float(), nullable=True))
    op.create_index(op.f('ix_leads_expected_value'), 'leads', ['expected_value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_expected_value'), table_name='leads')
    op.drop_column('leads', 'expected_value')
    op.drop_column('leads', 'value')
    op.drop_column('leads', 'sizing_reason')
    op.drop_column('leads', 'recommended_kwh')
    op.drop_column('leads', 'battery_values')
    op.drop_column('leads', 'load_zone')
    # ### end Alembic commands ###
