"""add cell load zone

Revision ID: 3fe466382c7d
Revises: 248d98c2a1a8
Create Date: 2026-09-26 17:08:41.550779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fe466382c7d'
down_revision: Union[str, Sequence[str], None] = '248d98c2a1a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cells', sa.Column('load_zone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cells', 'load_zone')
    # ### end Alembic commands ###
