"""add propensity

Revision ID: 248c01927d1b
Revises: b3c60ca08dd4
Create Date: 2026-09-26 21:08:00.373247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '248c01927d1b'
down_revision: Union[str, Sequence[str], None] = 'b3c60ca08dd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('propensity_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('product_cells', sa.Integer(), nullable=False),
    sa.Column('other_cells', sa.Integer(), nullable=False),
    sa.Column('model_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_propensity_imports'))
    )
    op.create_table('cell_propensities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('h3_index', sa.String(length=15), nullable=False),
    sa.Column('propensity_score', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=80), nullable=False),
    sa.Column('feature_version', sa.String(length=40), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['propensity_imports.id'], name=op.f('fk_cell_propensities_import_id_propensity_imports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cell_propensities')),
    sa.UniqueConstraint('h3_index', 'model_version', 'scored_at', name=op.f('uq_cell_propensities_h3_index'))
    )
    op.create_index(op.f('ix_cell_propensities_h3_index'), 'cell_propensities', ['h3_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cell_propensities_h3_index'), table_name='cell_propensities')
    op.drop_table('cell_propensities')
    op.drop_table('propensity_imports')
    # ### end Alembic commands ###
