"""add baseline need

Revision ID: b3c60ca08dd4
Revises: e63d2a703c56
Create Date: 2026-09-26 20:57:09.019045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3c60ca08dd4'
down_revision: Union[str, Sequence[str], None] = 'e63d2a703c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baseline_need_references',
    sa.Column('h3_index', sa.String(length=15), nullable=False),
    sa.Column('county_fips', sa.String(length=5), nullable=True),
    sa.Column('outage_input', sa.Float(), nullable=True),
    sa.Column('weather_input', sa.Float(), nullable=True),
    sa.Column('raw', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('h3_index', name=op.f('pk_baseline_need_references'))
    )
    op.create_table('cell_baseline_needs',
    sa.Column('h3_index', sa.String(length=15), nullable=False),
    sa.Column('outage_input', sa.Float(), nullable=True),
    sa.Column('weather_input', sa.Float(), nullable=True),
    sa.Column('raw', sa.Float(), nullable=True),
    sa.Column('baseline_need', sa.Float(), nullable=True),
    sa.Column('dominant_driver', sa.String(length=10), nullable=True),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('h3_index', name=op.f('pk_cell_baseline_needs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cell_baseline_needs')
    op.drop_table('baseline_need_references')
    # ### end Alembic commands ###
