"""create grid tables

Revision ID: cb04fbba3a19
Revises: 89b253c2f650
Create Date: 2026-09-25 21:32:39.115988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb04fbba3a19'
down_revision: Union[str, Sequence[str], None] = '89b253c2f650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grid_prices',
    sa.Column('settlement_point', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=2), nullable=False),
    sa.Column('interval_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('settlement_point', 'market', 'interval_start', name=op.f('pk_grid_prices'))
    )
    op.create_table('grid_zone_metrics',
    sa.Column('settlement_point', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('grid_value_score', sa.Float(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('series', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('settlement_point', name=op.f('pk_grid_zone_metrics'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grid_zone_metrics')
    op.drop_table('grid_prices')
    # ### end Alembic commands ###
