"""add consumption estimate columns

Revision ID: 93d872d30219
Revises: c463800be556
Create Date: 2026-09-26 13:14:30.879907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93d872d30219'
down_revision: Union[str, Sequence[str], None] = 'c463800be556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('consumption', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('leads', sa.Column('annual_kwh', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('bedrooms', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('full_baths', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('half_baths', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('stories', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'stories')
    op.drop_column('properties', 'half_baths')
    op.drop_column('properties', 'full_baths')
    op.drop_column('properties', 'bedrooms')
    op.drop_column('leads', 'annual_kwh')
    op.drop_column('leads', 'consumption')
    # ### end Alembic commands ###
