"""add forecast signals

Revision ID: d9ca3838700e
Revises: de8c18ea4e47
Create Date: 2026-09-26 20:16:12.547364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9ca3838700e'
down_revision: Union[str, Sequence[str], None] = 'de8c18ea4e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_points',
    sa.Column('h3_index', sa.String(length=15), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('office', sa.String(length=3), nullable=False),
    sa.Column('grid_x', sa.Integer(), nullable=False),
    sa.Column('grid_y', sa.Integer(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('h3_index', name=op.f('pk_forecast_points'))
    )
    op.create_table('forecast_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('points_ok', sa.Integer(), server_default='0', nullable=False),
    sa.Column('points_failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('spc_ok', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('spc_error', sa.Text(), nullable=True),
    sa.Column('point_errors', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast_runs'))
    )
    op.create_index(op.f('ix_forecast_runs_started_at'), 'forecast_runs', ['started_at'], unique=False)
    op.create_table('forecast_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('h3_index', sa.String(length=15), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('peak_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('label', sa.String(length=10), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('replaced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['forecast_runs.id'], name=op.f('fk_forecast_signals_run_id_forecast_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast_signals'))
    )
    op.create_index(op.f('ix_forecast_signals_h3_index'), 'forecast_signals', ['h3_index'], unique=False)
    op.create_index(op.f('ix_forecast_signals_run_id'), 'forecast_signals', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecast_signals_run_id'), table_name='forecast_signals')
    op.drop_index(op.f('ix_forecast_signals_h3_index'), table_name='forecast_signals')
    op.drop_table('forecast_signals')
    op.drop_index(op.f('ix_forecast_runs_started_at'), table_name='forecast_runs')
    op.drop_table('forecast_runs')
    op.drop_table('forecast_points')
    # ### end Alembic commands ###
