"""add weather features

Revision ID: f7ad34fcf21e
Revises: 7875e5f2f5a4
Create Date: 2026-09-26 19:39:01.483311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7ad34fcf21e'
down_revision: Union[str, Sequence[str], None] = '7875e5f2f5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('county_temperature_features',
    sa.Column('county_fips', sa.String(length=5), nullable=False),
    sa.Column('county_name', sa.String(length=60), nullable=True),
    sa.Column('data_through', sa.Date(), nullable=False),
    sa.Column('heat_days_100f_5y', sa.Integer(), nullable=False),
    sa.Column('heat_days_95f_5y', sa.Integer(), nullable=False),
    sa.Column('cold_days_28f_5y', sa.Integer(), nullable=False),
    sa.Column('cold_days_32f_5y', sa.Integer(), nullable=False),
    sa.Column('heat_days_100f_365d', sa.Integer(), nullable=False),
    sa.Column('heat_days_95f_365d', sa.Integer(), nullable=False),
    sa.Column('cold_days_28f_365d', sa.Integer(), nullable=False),
    sa.Column('cold_days_32f_365d', sa.Integer(), nullable=False),
    sa.Column('heat_100f_pctl', sa.Float(), nullable=True),
    sa.Column('cold_28f_pctl', sa.Float(), nullable=True),
    sa.Column('temperature_exposure', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('county_fips', name=op.f('pk_county_temperature_features'))
    )
    op.create_table('storm_features',
    sa.Column('h3_index', sa.String(length=15), nullable=False),
    sa.Column('resolution', sa.SmallInteger(), nullable=False),
    sa.Column('data_through', sa.Date(), nullable=False),
    sa.Column('warning_days_5y', sa.Integer(), nullable=False),
    sa.Column('warning_days_365d', sa.Integer(), nullable=False),
    sa.Column('severe_thunderstorm_warnings_5y', sa.Integer(), nullable=False),
    sa.Column('tornado_warnings_5y', sa.Integer(), nullable=False),
    sa.Column('extreme_wind_warnings_5y', sa.Integer(), nullable=False),
    sa.Column('issuing_office', sa.String(length=3), nullable=True),
    sa.Column('storm_exposure', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('h3_index', name=op.f('pk_storm_features'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storm_features')
    op.drop_table('county_temperature_features')
    # ### end Alembic commands ###
