"""add live weather signals

Revision ID: fc2244d1589a
Revises: f7ad34fcf21e
Create Date: 2026-09-26 19:51:53.972847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc2244d1589a'
down_revision: Union[str, Sequence[str], None] = 'f7ad34fcf21e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('live_weather_signals',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('event', sa.String(length=60), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('certainty', sa.String(length=20), nullable=True),
    sa.Column('urgency', sa.String(length=20), nullable=True),
    sa.Column('message_type', sa.String(length=20), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('sender', sa.String(length=120), nullable=True),
    sa.Column('zones', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('onset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('geometry', Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('geometry_source', sa.String(length=10), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_live_weather_signals'))
    )
    op.create_geospatial_index('idx_live_weather_signals_geometry', 'live_weather_signals', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('live_weather_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alerts_total', sa.Integer(), nullable=True),
    sa.Column('signals_kept', sa.Integer(), nullable=True),
    sa.Column('superseded', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_live_weather_snapshots'))
    )
    op.create_index(op.f('ix_live_weather_snapshots_fetched_at'), 'live_weather_snapshots', ['fetched_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_live_weather_snapshots_fetched_at'), table_name='live_weather_snapshots')
    op.drop_table('live_weather_snapshots')
    op.drop_geospatial_index('idx_live_weather_signals_geometry', table_name='live_weather_signals', postgresql_using='gist', column_name='geometry')
    op.drop_geospatial_table('live_weather_signals')
    # ### end Alembic commands ###
