"""add grid conditions

Revision ID: e63d2a703c56
Revises: d9ca3838700e
Create Date: 2026-09-26 20:35:06.221669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e63d2a703c56'
down_revision: Union[str, Sequence[str], None] = 'd9ca3838700e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grid_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('eea_level', sa.SmallInteger(), nullable=True),
    sa.Column('prc_mw', sa.Integer(), nullable=True),
    sa.Column('capacity_mw', sa.Integer(), nullable=True),
    sa.Column('demand_mw', sa.Integer(), nullable=True),
    sa.Column('margin_forecast_min_mw', sa.Integer(), nullable=True),
    sa.Column('margin_forecast_min_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grid_conditions'))
    )
    op.create_index(op.f('ix_grid_conditions_fetched_at'), 'grid_conditions', ['fetched_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grid_conditions_fetched_at'), table_name='grid_conditions')
    op.drop_table('grid_conditions')
    # ### end Alembic commands ###
