"""add outage features

Revision ID: 7875e5f2f5a4
Revises: 3fe466382c7d
Create Date: 2026-09-26 17:39:08.139019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '7875e5f2f5a4'
down_revision: Union[str, Sequence[str], None] = '3fe466382c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('county_outage_features',
    sa.Column('county_fips', sa.String(length=5), nullable=False),
    sa.Column('county_name', sa.String(length=60), nullable=True),
    sa.Column('modeled_customers', sa.Integer(), nullable=False),
    sa.Column('data_through', sa.Date(), nullable=False),
    sa.Column('years_observed', sa.SmallInteger(), nullable=False),
    sa.Column('in_reference', sa.Boolean(), nullable=False),
    sa.Column('hours_per_customer_365d', sa.Float(), nullable=True),
    sa.Column('outage_events_365d', sa.Integer(), nullable=True),
    sa.Column('major_outage_events_365d', sa.Integer(), nullable=True),
    sa.Column('peak_pct_out_365d', sa.Float(), nullable=True),
    sa.Column('hours_per_customer_5y', sa.Float(), nullable=True),
    sa.Column('outage_events_5y', sa.Integer(), nullable=True),
    sa.Column('major_outage_events_5y', sa.Integer(), nullable=True),
    sa.Column('peak_pct_out_5y', sa.Float(), nullable=True),
    sa.Column('last_observed_major_outage_on', sa.Date(), nullable=True),
    sa.Column('hours_per_customer_pctl', sa.Float(), nullable=True),
    sa.Column('observed_exposure', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('county_fips', name=op.f('pk_county_outage_features'))
    )
    op.create_table('utility_reliability_features',
    sa.Column('utility_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('utility_name', sa.String(length=120), nullable=False),
    sa.Column('ownership', sa.String(length=40), nullable=True),
    sa.Column('customers', sa.Float(), nullable=True),
    sa.Column('data_through_year', sa.SmallInteger(), nullable=False),
    sa.Column('years_used', sa.SmallInteger(), nullable=False),
    sa.Column('saidi_wo_med_5y', sa.Float(), nullable=True),
    sa.Column('saifi_wo_med_5y', sa.Float(), nullable=True),
    sa.Column('saidi_w_med_5y', sa.Float(), nullable=True),
    sa.Column('saifi_w_med_5y', sa.Float(), nullable=True),
    sa.Column('reliability_need', sa.Float(), nullable=True),
    sa.Column('yearly', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('utility_id', name=op.f('pk_utility_reliability_features'))
    )
    op.add_column('cells', sa.Column('county_fips', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cells', 'county_fips')
    op.drop_table('utility_reliability_features')
    op.drop_table('county_outage_features')
    # ### end Alembic commands ###
