"""add property h3_index

Revision ID: ce988e3f631f
Revises: 93d872d30219
Create Date: 2026-09-26 23:51:34.785315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce988e3f631f'
down_revision: Union[str, Sequence[str], None] = '93d872d30219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('h3_index', sa.String(length=15), nullable=True))
    op.create_index(op.f('ix_properties_h3_index'), 'properties', ['h3_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_h3_index'), table_name='properties')
    op.drop_column('properties', 'h3_index')
    # ### end Alembic commands ###
