"""add property features and location

Revision ID: b12dd9604f76
Revises: b3510885e558
Create Date: 2026-09-26 08:53:35.047235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b12dd9604f76'
down_revision: Union[str, Sequence[str], None] = 'b3510885e558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('has_solar', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('properties', sa.Column('has_pool', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('properties', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('lon', sa.Float(), nullable=True))
    op.create_index(op.f('ix_properties_lat'), 'properties', ['lat', 'lon'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_lat'), table_name='properties')
    op.drop_column('properties', 'lon')
    op.drop_column('properties', 'lat')
    op.drop_column('properties', 'has_pool')
    op.drop_column('properties', 'has_solar')
    # ### end Alembic commands ###
