"""create lead tables

Revision ID: b3510885e558
Revises: cb04fbba3a19
Create Date: 2026-09-25 23:47:19.488065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3510885e558'
down_revision: Union[str, Sequence[str], None] = 'cb04fbba3a19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meters',
    sa.Column('esiid', sa.String(length=40), nullable=False),
    sa.Column('tdsp', sa.String(length=40), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('zip', sa.String(length=5), nullable=True),
    sa.Column('county', sa.String(length=40), nullable=True),
    sa.Column('address_key', sa.Text(), nullable=True),
    sa.Column('premise_type', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('esiid', name=op.f('pk_meters'))
    )
    op.create_index(op.f('ix_meters_address_key'), 'meters', ['address_key'], unique=False)
    op.create_table('permits',
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('permit_id', sa.String(length=80), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('zip', sa.String(length=5), nullable=True),
    sa.Column('address_key', sa.Text(), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('source', 'permit_id', name=op.f('pk_permits'))
    )
    op.create_index(op.f('ix_permits_address_key'), 'permits', ['address_key'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('county', sa.String(length=40), nullable=False),
    sa.Column('account', sa.String(length=40), nullable=False),
    sa.Column('situs_address', sa.Text(), nullable=True),
    sa.Column('situs_city', sa.Text(), nullable=True),
    sa.Column('situs_zip', sa.String(length=5), nullable=True),
    sa.Column('address_key', sa.Text(), nullable=True),
    sa.Column('owner_name', sa.Text(), nullable=True),
    sa.Column('mail_address', sa.Text(), nullable=True),
    sa.Column('state_class', sa.String(length=10), nullable=True),
    sa.Column('is_single_family', sa.Boolean(), nullable=False),
    sa.Column('homestead', sa.Boolean(), nullable=False),
    sa.Column('confidential', sa.Boolean(), nullable=False),
    sa.Column('market_value', sa.Float(), nullable=True),
    sa.Column('heated_sqft', sa.Float(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_properties')),
    sa.UniqueConstraint('county', 'account', name=op.f('uq_properties_county'))
    )
    op.create_index(op.f('ix_properties_address_key'), 'properties', ['address_key'], unique=False)
    op.create_table('source_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=60), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fingerprint', sa.Text(), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('inserted', sa.Integer(), nullable=True),
    sa.Column('updated', sa.Integer(), nullable=True),
    sa.Column('raw_path', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_runs'))
    )
    op.create_index(op.f('ix_source_runs_source_id'), 'source_runs', ['source_id'], unique=False)
    op.create_table('leads',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('drivers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasons', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='new', nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_leads_property_id_properties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('property_id', name=op.f('pk_leads'))
    )
    op.create_index(op.f('ix_leads_score'), 'leads', ['score'], unique=False)
    op.create_index(op.f('ix_leads_triggered_at'), 'leads', ['triggered_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_triggered_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_score'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_source_runs_source_id'), table_name='source_runs')
    op.drop_table('source_runs')
    op.drop_index(op.f('ix_properties_address_key'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_permits_address_key'), table_name='permits')
    op.drop_table('permits')
    op.drop_index(op.f('ix_meters_address_key'), table_name='meters')
    op.drop_table('meters')
    # ### end Alembic commands ###
