"""create cells

Revision ID: 248d98c2a1a8
Revises: c463800be556
Create Date: 2026-09-26 16:44:21.515297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '248d98c2a1a8'
down_revision: Union[str, Sequence[str], None] = 'c463800be556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('cells',
    sa.Column('h3_index', sa.String(length=15), nullable=False),
    sa.Column('resolution', sa.SmallInteger(), nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_lng', sa.Float(), nullable=False),
    sa.Column('geometry', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('h3_index', name=op.f('pk_cells'))
    )
    op.create_geospatial_index('idx_cells_geometry', 'cells', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index('idx_cells_geometry', table_name='cells', postgresql_using='gist', column_name='geometry')
    op.drop_geospatial_table('cells')
    # ### end Alembic commands ###
    # The postgis extension stays: dropping it would break any other spatial objects.
